#!/usr/bin/python3
import os
import atexit
import readline

# the location of this file is defined in $PYTHONSTARTUP

history = os.path.join(os.path.expanduser('~'), '.cache/python_history')
try:
    readline.read_history_file(history)
except OSError:
    pass

def write_history():
    try:
        readline.write_history_file(history)
    except OSError:
        pass

atexit.register(write_history)

import math
import os
import sys

