#!/bin/sh

case "$(pacman -Q picom)" in
  *picom-jonaburg*) add_file="./picom.jonaburg.conf" ;;
  *) add_file="" ;;
esac

[ -f "../themes/$RECONF_THEME/picom.$RECONF_THEME.conf" ] \
  && theme_file="../themes/$RECONF_THEME/picom.$RECONF_THEME.conf" \
  || theme_file="./picom.default-theme.conf"

echo "./picom.conf+$theme_file+$add_file -> $XDG_CONFIG_HOME/picom.conf"
cat "./picom.conf" "$theme_file" "$add_file" 2>/dev/null \
  | ../reconf > "$XDG_CONFIG_HOME/picom.conf"

