#!/bin/sh

case "$(pacman -Q picom)" in
  *picom-jonaburg-git*)
    echo "./picom.conf+./picom.jonaburg.conf -> $XDG_CONFIG_HOME/picom.conf"
    cat "./picom.conf" "./picom.jonaburg.conf" > "$XDG_CONFIG_HOME/picom.conf" ;;
  *)
    cp -v "./picom.conf" "$XDG_CONFIG_HOME/picom.conf" ;;
esac

