#!/bin/sh

SXHKD_CONFIG_DIR="$XDG_CONFIG_HOME/sxhkd"
POLYBAR_CONFIG_DIR="$XDG_CONFIG_HOME/polybar"

[ -d "$SXHKD_CONFIG_DIR" ] || mkdir -p "$SXHKD_CONFIG_DIR"
[ -d "$POLYBAR_CONFIG_DIR" ] || mkdir -p "$POLYBAR_CONFIG_DIR"

echo "./sxhkdrc -> $SXHKD_CONFIG_DIR/sxhkdrc"
cat "./sxhkdrc" | ../reconf "../defaults" "../$1.prefs" \
	> "$SXHKD_CONFIG_DIR/sxhkdrc"
cp -v "./libinput-gestures.conf" "$XDG_CONFIG_HOME/libinput-gestures.conf"
#echo "./polybar.conf > $POLYBAR_CONFIG_DIR/config"
#cat "./polybar.conf" | ../reconf "../defaults" "../$1.prefs" \
#    > "$POLYBAR_CONFIG_DIR/config"

