#!/bin/sh

SXHKD_CONFIG_DIR="$XDG_CONFIG_HOME/sxhkd"
DUNST_CONFIG_DIR="$XDG_CONFIG_HOME/dunst"
ICONS_DIR="$XDG_DATA_HOME/icons/notify"

[ -d "$SXHKD_CONFIG_DIR" ] || mkdir -p "$SXHKD_CONFIG_DIR"
[ -d "$DUNST_CONFIG_DIR" ] || mkdir -p "$DUNST_CONFIG_DIR"
[ -d "$ICONS_DIR" ] || mkdir -p "$ICONS_DIR"

echo "./sxhkdrc -> $SXHKD_CONFIG_DIR/sxhkdrc"
cat "./sxhkdrc" | ../reconf "../defaults" "../$1.prefs" \
	> "$SXHKD_CONFIG_DIR/sxhkdrc"
cp -v "./libinput-gestures.conf" "$XDG_CONFIG_HOME/libinput-gestures.conf"
cp -v "./icons/"* "$ICONS_DIR/"
echo "./dunstrc -> $DUNST_CONFIG_DIR/dunstrc"
cat "./dunstrc" | ../reconf "../defaults" "../$1.prefs" \
	> "$DUNST_CONFIG_DIR/dunstrc"

