#!/bin/sh

CONFIG_DIR="$HOME/.config/neomutt"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

cp -v "./neomuttrc" "$CONFIG_DIR/"
cp -v "./${RECONF_COLROSCHEME:-dracula}.muttrc" "$CONFIG_DIR/"
cp -v "./keybinds.muttrc" "$CONFIG_DIR/"
cp -v "./mailcap" "$CONFIG_DIR/"

echo "NB: you need \"login-*.muttrc\" and \"aliases.muttrc\" to be in $CONFIG_DIR as well"

