#!/bin/sh

# ------------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------------
export DOTFILES_REPO="${DOTFILES_REPO:-$HOME/Dotfiles}"
if [ ! -d "$DOTFILES_REPO" ]; then
  echo "$DOTFILES_REPO does not exist"
  exit 1
fi

# ------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------
install_subfolder(){
  if [ -z "$1" ]; then
    echo "\033[31mYou need to provide a package to install\033[0m"
    exit 1
  fi

  if [ ! -d "$1" ]; then
    echo "\033[31m$1 is not a directory\033[0m"
    return
  fi

  if [ ! -x "$1/install" ]; then
    echo "\033[31minstall script for $1 does not exist or is not executable, aborting\033[0m"
    return
  fi

  if [ -z "$2" ]; then
    if [ -f "$XDG_DATA_HOME/conf-pc-name" ]; then
      machine="$(cat $XDG_DATA_HOME/conf-pc-name)"
      echo "using $XDG_DATA_HOME/conf-pc-name for machine name"
    else
      machine="$(cat /etc/hostname)"
      echo "using /etc/hostname for machine name"
    fi
  else
    machine="$2"
    echo "using provided argument for machine name"
  fi

  echo "Sourcing settings..."
  . "./$machine.prefs2"
  . "./themes/$RECONF_THEME/$RECONF_THEME.prefs2"

  echo "Installing \033[34m$1\033[0m for \033[33m$machine\033[0m..."
  cd "$1"
  ./install "$machine"
  cd "$OLDPWD"
}

# ------------------------------------------------------------------
# ACTUAL SCRIPT
# ------------------------------------------------------------------
cd "$DOTFILES_REPO"
install_subfolder "$@"

