#!/usr/bin/env python3
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
# 
# replace strings in config files with settings
# all environmental variables that start with RECONF_ are considered settings
#                                                          

import os
import sys

# read settings from the environment
def read_settings():
    settings = {}
    for key in os.environ:
        if key.startswith("RECONF_"):
            settings[key[7:]] = os.environ[key]
    return settings

if __name__ == "__main__":
    settings = read_settings()

    # read data
    data = sys.stdin.read()

    # configure
    for key in settings:
        data = data.replace(f"+{key}+", settings[key])

    # minify and output
    for l in data.split("\n"):
        if l.startswith("#"):
            continue
        if l == "":
            continue
        sys.stdout.write(l + "\n")

