#!/bin/sh

[ "$1" = "pinguin" ] \
  && file="starship.toml" \
  || file="starship.$1.toml"

echo "./$file -> $XDG_CONFIG_HOME/starship.toml"
cat "./$file" | ../reconf "../defaults" "../$1.prefs" > "$XDG_CONFIG_HOME/starship.toml"

