#!/bin/sh

echo "default:"
. "./icons.prefs2"
echo "./starship.toml -> $XDG_CONFIG_HOME/starship.toml"
cat "./starship.toml" | ../reconf \
    > "$XDG_CONFIG_HOME/starship.toml"

echo

echo "ascii only:"
. "./ascii.prefs2"
echo "./starship.toml -> $XDG_CONFIG_HOME/starship-ascii.toml"
cat "./starship.toml" | ../reconf \
    > "$XDG_CONFIG_HOME/starship-ascii.toml"

