#        _                        _            ___  _  _
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|
#
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#
# starship config file

add_newline = false
format = """[\\[](blue) $username[@](red)$hostname [\\]](blue) in $directory$git_status$git_branch $python$golang$nodejs
$custom$time $jobs$cmd_duration$character"""

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "$hostname"
disabled = false

[directory]
truncation_length = 5
truncation_symbol = ".../"
style = "bold cyan"
read_only_style = "red bold"
read_only = "[ro]"
home_symbol = " "
format = "[$path]($style) [$read_only]($read_only_style) "

[git_status]
format = "[git](blue):\\[$ahead_behind $staged$untracked$modified$renamed$deleted$conflicted$stashed\\]"
ahead = "[A](yellow)"
behind = "[B](red)"
diverged = "[D](red)"
up_to_date = "[O](green)"
conflicted = "[=](red)"
untracked = "[?](red)"
stashed = "$"
modified = "[!](red)"
staged = "[+](cyan)"
renamed = "[>](red)"
deleted = "[x](red)"

[git_branch]
style = "yellow"
symbol = "||"
format = " on [$symbol$branch]($style)"

[jobs]
format = "[$symbol$number]($style) "
symbol = "bg "
style = "blue bold"
number_threshold = 1

[character]
#success_symbol = "[ ](bold green)"
#success_symbol = "[ ](bold green)"
success_symbol = "[>>> ](bold green)"
error_symbol = "[! ](bold red)"
#error_symbol = "[ ](bold red)"
#error_symbol = "[ ](bold red)"
vicmd_symbol = "[vim ](bold blue)"

[time]
disabled = false
format = "\\[[$time]($style)\\]"
time_format = "%a, %d %b %H:%M"

[custom.lf_level]
command = "echo :lf$LF_LEVEL: "
when = "[ ! -z $LF_LEVEL ]"
style = "cyan"
format = "[$output]($style)"

