#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

echo "./env.sh -> $CONFIG_DIR/env.sh"
cat "./_header" "./env.sh" | ../reconf \
    > "$CONFIG_DIR/env.sh"

echo "./colors.sh -> $CONFIG_DIR/colors.sh"
sed -E '/^#/d; /^$/d' "./_header" "./colors.sh" >"$CONFIG_DIR/colors.sh"

