#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

echo "./env -> $CONFIG_DIR/env.sh"
cat "./binsh" "./env" | ../reconf \
    > "$CONFIG_DIR/env.sh"

echo "./colors.sh -> $CONFIG_DIR/colors.sh"
sed -E '/^#/d; /^$/d' "./colors.sh" >"$CONFIG_DIR/colors.sh"

