#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/nvim"
PAGER_DIR="$XDG_CONFIG_HOME/nvimpager"

# NVIM {{{
create_symlink(){
  ln -sv "$DOTFILES_REPO/nvim" "$CONFIG_DIR"
}

if [ ! -e "$CONFIG_DIR" ]; then
  create_symlink
else
  if [ ! -h "$CONFIG_DIR" ] || [ ! "$(readlink "$CONFIG_DIR")" = "$DOTFILES_REPO/nvim" ]; then
    rm -rfv "$CONFIG_DIR"
    create_symlink
  fi
fi
# }}}

# NVIMPAGER {{{
echo "Installing nvimpager"

[ -d "$PAGER_DIR" ] || mkdir -vp "$PAGER_DIR"

[ -e "$PAGER_DIR/init.vim" ] || ln -sv "$CONFIG_DIR/common.vim" "$PAGER_DIR/init.vim"

[ -e "$PAGER_DIR/ftdetect" ] || ln -sv "$CONFIG_DIR/ftdetect" "$PAGER_DIR/ftdetect"
[ -e "$PAGER_DIR/syntax" ] || ln -sv "$CONFIG_DIR/syntax" "$PAGER_DIR/syntax"
[ -e "$PAGER_DIR/colors" ] || ln -sv "$CONFIG_DIR/colors" "$PAGER_DIR/colors"
# }}}

