#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/nvim"

[ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"

for f in *.vim; do
  echo "./$f > $CONFIG_DIR/$f"
  sed '/^$/d; /^"/d' "./$f" >"$CONFIG_DIR/$f"
done

echo "Installing nvimpager"
mkdir -vp "$XDG_CONFIG_HOME/nvimpager"
ln -sv "$XDG_DATA_HOME/nvim" "$XDG_DATA_HOME/nvimpager"
echo "./common.vim > $XDG_CONFIG_HOME/nvimpager/init.vim"
sed '/^$/d; /^"/d' "./common.vim" >"$XDG_CONFIG_HOME/nvimpager/init.vim"

