#!/bin/bash
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021-2022 alexcoder04 <https://github.com/alexcoder04>
# 
# i3 config installer
# it became quite complex over the time, supporting multiple themes (modes)
# and different machines

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/i3"
THEME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bumblebee-status/themes"
I3BLOCKS_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks"
MACHINE="$1"

mkdir -vp "$CONFIG_DIR"
cp -v "./lock.png" "$CONFIG_DIR/lock.png"

if [ -z "$RECONF_I3_MODE" ]; then
  [ -z "$RIM" ] \
    && export RECONF_I3_MODE="kherson" \
    || export RECONF_I3_MODE="$RIM"
fi

# -----------------------------------------------------------------------------
# HELPER FUNCTIONS
# -----------------------------------------------------------------------------
print_install_message(){
    echo -e "Installing i3 in \033[36m$1\033[0m mode"
}

# -----------------------------------------------------------------------------
# MACHINE SPECIFIC I3BLOCKS
# -----------------------------------------------------------------------------
install_i3blocks(){
  if [ -f "./blocks-$MACHINE.conf" ]; then
    file="./blocks-$MACHINE.conf"
  else
    file="./blocks-default.conf"
  fi
  mkdir -vp "$I3BLOCKS_DIR"
  echo "$file -> $I3BLOCKS_DIR/config"
  ../reconf <"$file" >"$I3BLOCKS_DIR/config"
}

# -----------------------------------------------------------------------------
# BUMBLEBEE-STATUS INSTALLER
# -----------------------------------------------------------------------------
install_bumblebee-status(){
  mkdir -vp "$THEME_DIR"
  ./bumblebee-theme-gen.py >"$THEME_DIR/powerline-custom.json"
  cp -v "./bumblebee-status.conf" "${XDG_CONFIG_HOME:-$HOME/.config}"
}

# -----------------------------------------------------------------------------
# KHERSON INSTALLER
# -----------------------------------------------------------------------------
install_kherson(){
    config_folder="${XDG_CONFIG_HOME:-$HOME/.config}/kherson"
    mkdir -vp "$config_folder"
    cp -v "./kherson.yml" "$config_folder/config.yml"
}

case "$RECONF_I3_MODE" in
  # -----------------------------------------------------------------------------
  # I3BLOCKS MODE
  # -----------------------------------------------------------------------------
  blocks) 
    print_install_message "BLOCKS"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X i3blocks"

    echo "pre + x11-pre + main + bar + x11-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_i3blocks

    ;;

  # -----------------------------------------------------------------------------
  # POLYBAR MODE
  # -----------------------------------------------------------------------------
  polybar)
    print_install_message "POLYBAR"
    export RECONF_BARS_LAUNCHER_COMMAND="$RECONF_PRE_X bar-launch i3-polybar"

    echo "pre + x11-pre + main + x11-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./main.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    ;;

  # -----------------------------------------------------------------------------
  # POWERLINE (BUMBLEBEE-STATUS) MODE
  # -----------------------------------------------------------------------------
  powerline)
    print_install_message "POWERLINE"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X bumblebee-status"

    echo "pre + x11-pre + main + bar + x1-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_bumblebee-status

    ;;

  # -----------------------------------------------------------------------------
  # KHERSON MODE
  # -----------------------------------------------------------------------------
  kherson)
    print_install_message "KHERSON"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X kherson"

    echo "pre + x11-pre + main + bar + x11-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_kherson

    ;;

  # -----------------------------------------------------------------------------
  # SWAY (I3BLOCKS) MODE
  # -----------------------------------------------------------------------------
  sway-blocks)
    print_install_message "SWAY"
    export CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X i3blocks"

    echo "pre + wayland-pre + main + bar + wayland-after + [keys] + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-wayland-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-wayland-after.config" \
        <(../sxhkd/sxhkdtosway.py <../sxhkd/sxhkdrc) \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_i3blocks

    ;;

  # -----------------------------------------------------------------------------
  # SWAY (POWERLINE) MODE
  # -----------------------------------------------------------------------------
  sway-powerline)
    print_install_message "SWAY-POWERLINE"
    export CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X bumblebee-status"

    echo "pre + wayland-pre + main + bar + wayland-after + [keys] + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-wayland-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-wayland-after.config" \
        <(../sxhkd/sxhkdtosway.py <../sxhkd/sxhkdrc) \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_bumblebee-status

    ;;

  # -----------------------------------------------------------------------------
  # SWAY (KHERSON) MODE
  # -----------------------------------------------------------------------------
  sway-kherson | sway)
    print_install_message "SWAY-KHERSON"
    export CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X kherson"

    echo "pre + wayland-pre + main + bar + wayland-after + [keys] + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-wayland-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-wayland-after.config" \
        <(../sxhkd/sxhkdtosway.py <../sxhkd/sxhkdrc) \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_kherson

    ;;

  *)
    echo "Unknown mode!"
    exit 1 ;;
esac

echo "YOU NEED TO RESTART I3 TO APPLY THE NEW CONFIGURATION!"

