#!/bin/bash
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
# 
# i3 config installer
# it became quite complex over the time, supporting multiple themes (modes)
# and different machines

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/i3"
THEME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bumblebee-status/themes"
MACHINE="$1"
[ -z "$RECONF_I3_MODE" ] && RECONF_I3_MODE="${RIM:-blocks}"

mkdir -vp "$CONFIG_DIR"
mkdir -vp "$THEME_DIR"

# -----------------------------------------------------------------------------
# MACHINE_SPECIFIC I3BLOCKS
# -----------------------------------------------------------------------------
install_i3blocks(){
  if [ -f "./blocks-$MACHINE.conf" ]; then
      file="./blocks-$MACHINE.conf"
  else
      file="./blocks-default.conf"
  fi
  echo "$file -> $CONFIG_DIR/i3blocks.conf"
  cat "$file" | ../reconf > "$CONFIG_DIR/i3blocks.conf"
}

# -----------------------------------------------------------------------------
# BUMBLEBEE-STATUS INSTALLER
# -----------------------------------------------------------------------------
install_bumblebee-status(){
  ./bumblebee-theme-gen.py >"$THEME_DIR/powerline-custom.json"
  cp -v "./start_bumblebee" "$CONFIG_DIR/start_bumblebee"
  chmod -v +x "$CONFIG_DIR/start_bumblebee"
}

# -----------------------------------------------------------------------------
# DEFAULT MODE IS I3BLOCKS
# -----------------------------------------------------------------------------
export RECONF_I3_MODE="${RECONF_I3_MODE:-blocks}"

case "$RECONF_I3_MODE" in
  # -----------------------------------------------------------------------------
  # I3BLOCKS MODE
  # -----------------------------------------------------------------------------
  blocks) 
    echo "Installing i3 in BLOCKS mode"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X i3blocks -c ~/.config/i3/i3blocks.conf"

    echo "pre + x11-pre + main + bar + x11-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_i3blocks

    ;;

  # -----------------------------------------------------------------------------
  # POLYBAR MODE
  # -----------------------------------------------------------------------------
  polybar)
    echo "Installing i3 in POLYBAR mode"
    export RECONF_BARS_LAUNCHER_COMMAND="$RECONF_PRE_X bar-launch i3-polybar"

    echo "pre + x11-pre + main + x11-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./main.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    ;;

  # -----------------------------------------------------------------------------
  # POWERLINE (BUMBLEBEE-STATUS) MODE
  # -----------------------------------------------------------------------------
  powerline)
    echo "Installing i3 in POWERLINE mode"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X $CONFIG_DIR/start_bumblebee"

    echo "pre + x11-pre + main + bar + x1-after + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-x11-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-x11-after.config" \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_bumblebee-status

    ;;

  # -----------------------------------------------------------------------------
  # SWAY (I3BLOCKS) MODE
  # -----------------------------------------------------------------------------
  sway | sway-blocks)
    echo "Installing i3 in SWAY mode"
    export CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X i3blocks -c ~/.config/sway/i3blocks.conf"

    echo "pre + wayland-pre + main + bar + wayland-after + [keys] + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-wayland-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-wayland-after.config" \
        <(../sxhkd/sxhkdtosway.py <../sxhkd/sxhkdrc) \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_i3blocks

    ;;

  # -----------------------------------------------------------------------------
  # SWAY (POWERLINE) MODE
  # -----------------------------------------------------------------------------
  sway-powerline)
    echo "Installing i3 in SWAY-POWERLINE mode"
    export CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
    export RECONF_I3_STATUS_COMMAND="$RECONF_PRE_X $CONFIG_DIR/start_bumblebee"

    echo "pre + wayland-pre + main + bar + wayland-after + [keys] + [addons] -> $CONFIG_DIR/config"
    cat \
        "./i3-pre.config" \
        "./i3-wayland-pre.config" \
        "./i3-main.config" \
        "./i3-bar.config" \
        "./i3-wayland-after.config" \
        <(../sxhkd/sxhkdtosway.py <../sxhkd/sxhkdrc) \
        $RECONF_I3_ADDONS \
        | ../reconf > "$CONFIG_DIR/config"

    install_bumblebee-status

    ;;

  *)
    echo "Unknown mode!"
    exit 1 ;;
esac

# -----------------------------------------------------------------------------
# EVERYONE NEEDS THE LOCK SCREEN ICON
# -----------------------------------------------------------------------------
cp -v "./lock.png" "$CONFIG_DIR/lock.png"

echo "YOU NEED TO RESTART I3 TO APPLY THE NEW CONFIGURATION!"

