#!/bin/sh

SOURCE_FILE="../i3-base/config"
CONFIG_DIR="$XDG_CONFIG_HOME/i3"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"
[ -d "$POLY_CONFIG_DIR" ] || mkdir -vp "$POLY_CONFIG_DIR"

echo "$SOURCE_FILE -> $CONFIG_DIR/config"
export BARS_LAUNCHER_COMMAND="bar-launch i3-polybar"
cat "$SOURCE_FILE" | ../reconf \
	> "$CONFIG_DIR/config"
../install polybar
echo "NOTE: YOU NEED TO RESTART I3 TO APPLY THE NEW CONFIGURATION"

