#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/X11"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

echo "./Xresources -> $CONFIG_DIR/Xresources"
cat "./Xresources" | ../reconf \
    > "$CONFIG_DIR/Xresources"
xrdb "$CONFIG_DIR/Xresources"

wm_init_file="./$RECONF_THEME/wm-init"
[ -f "$wm_init_file" ] \
    && mkdir -vp "$XDG_CONFIG_HOME/wm-init" \
    && cp -v "$wm_init_file" "$XDG_CONFIG_HOME/wm-init/theme"

