#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/polybar"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

echo "./config -> $CONFIG_DIR/config"
cat "./config" | ../reconf "../defaults" "../$1.prefs" \
	> "$CONFIG_DIR/config"

