#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/i3"

cat "../i3-base/config" | ../reconf "../defaults" "../$2.prefs" \
	> "$CONFIG_DIR/config"
cp -v "i3blocks.conf" "$CONFIG_DIR/i3blocks.conf"
echo "NOTE: YOU NEED TO RESTART I3 TO APPLY THE NEW CONFIGURATION"

