#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/zsh"

[ -d "$CONFIG_DIR" ] || mkdir -vp "$CONFIG_DIR"

echo "./zshrc -> $CONFIG_DIR/.zshrc"
cat "./zshrc" | ../reconf \
    > "$CONFIG_DIR/.zshrc"

echo "../sh/env -> $HOME/.zshenv"
cat "./_header" "../sh/env" | ../reconf \
    > "$HOME/.zshenv"

echo "../sh/aliases -> $CONFIG_DIR/aliases.zsh"
pre="$(pwd)"
cd "../sh" && ./aliases-gen "zsh" \
    > "$CONFIG_DIR/aliases.zsh"
cd "$pre"

cp -v ./*.zsh "$CONFIG_DIR/"

if [ -f "./startup.$1" ]; then
  cp -v "./startup.$1" "$CONFIG_DIR/startup.zsh"
else
  cp -v "./startup.default" "$CONFIG_DIR/startup.zsh"
fi

cp -v "./zprofile" "$CONFIG_DIR/.zprofile"

echo "creating bookmarks"
pre="$(pwd)"
cd "../bookmarks" && ./build zsh \
    > "$CONFIG_DIR/bookmarks.zsh"
cd "$pre"

echo "creating cache dir"
[ -d "$HOME/.cache/zsh" ] || mkdir -v "$HOME/.cache/zsh"

../install starship

