#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/zsh"

[ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"

echo "./zshrc -> $CONFIG_DIR/.zshrc"
cat "./zshrc" | ../reconf "../defaults" "../$1.prefs" > "$CONFIG_DIR/.zshrc"
echo "../sh/env -> $HOME/.zshenv"
cat "./_header" "../sh/env" | ../reconf "../defaults" "../$1.prefs" > "$HOME/.zshenv"
/bin/ls *.zsh | xargs -I{} sh -c "cat {} | ../reconf \"../defaults\" \"../$1.prefs\" > \"$CONFIG_DIR/{}\" && echo \"{} -> $CONFIG_DIR/{}\""
[ -d "$HOME/.cache/zsh" ] || mkdir -v "$HOME/.cache/zsh"

../install starship

