#!/usr/bin/zsh
#        _                        _            ___  _  _
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|
#
# Copyright (c) 2021-2022 alexcoder04 <https://github.com/alexcoder04>
#      
# zsh config

# ---------------------------------------------------------
# CHECK IF RUNNING IN INTERACTIVE MODE
# ---------------------------------------------------------
[[ -o interactive ]] || exit

# ---------------------------------------------------------
# SOURCE OTHER FILES
# --------------------------------------------------------- {{{
source "$ZDOTDIR/cursor.zsh"
source "$ZDOTDIR/abbreviations.zsh"
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/bookmarks.zsh"
source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/prompt.zsh"
[ -f "$XDG_CONFIG_HOME/colors.sh" ] && source "$XDG_CONFIG_HOME/colors.sh"
# }}}

# ---------------------------------------------------------
# HISTORY CONFIGURATION
# --------------------------------------------------------- {{{
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
HISTORY_IGNORE="(git add *|git commit *|* _bookmark-ls|mpv http*)"
HISTFILE="$XDG_CACHE_HOME/zsh/zsh_history"
HISTSIZE=15000
SAVEHIST=15000
# }}}

# ---------------------------------------------------------
# AUTOCOMPLETION
# --------------------------------------------------------- {{{
autoload -U compinit
zstyle :compinstall filename "$XDG_CONFIG_HOME/zsh/zshrc"
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
setopt globdots
# }}}

# ---------------------------------------------------------
# CD INTO FOLDER SELECTED USING LF OR FZF
# --------------------------------------------------------- {{{
lfcd(){
  tmp="${TMPDIR:-/tmp}/.lfcd"
  lf -last-dir-path="$tmp" "$@"
  [ -f "$tmp" ] || return
  dir="$(cat "$tmp")"
  rm -f "$tmp"
  [ -d "$dir" ] && cd "$dir"
}

fzfcd(){
  dest="$(cat "$DOTFILES_REPO/bookmarks/source-"* | awk '{print $2}' | sort | fzf)"
  [ -z "$dest" ] && return
  # maybe it's like $XDG_CONFIG_HOME
  dir="$(eval "echo $dest")"
  [ -d "$dir" ] && cd "$dir"
}
# }}}

# ---------------------------------------------------------
# KEYBINDINGS
# --------------------------------------------------------- {{{
KEYTIMEOUT=3
bindkey -v # vi mode
# vi navigation in menu
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
# edit command in editor
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

bindkey -s '^f' 'lfcd\n' # select folder to open with lf
bindkey -s '^o' 'fzfcd\n' # select folder to open with fzf
bindkey -s '^b' ' &>/dev/null & disown' # run command in the background
# }}}

# ---------------------------------------------------------
# OTHER SETTINGS
# ---------------------------------------------------------
setopt autocd
unsetopt beep extendedglob notify

# ---------------------------------------------------------
# SYNTAX HIGHLIGHTING
# ---------------------------------------------------------
if command -v pacman >/dev/null; then
  ZSH_SYNTAX="/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
else
  ZSH_SYNTAX="/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
[ -f "$ZSH_SYNTAX" ] && source "$ZSH_SYNTAX"
unset ZSH_SYNTAX

# ---------------------------------------------------------
# STARTUP STUFF IF NOT INSIDE LF
# ---------------------------------------------------------
[ -z "$LF_LEVEL" ] && source "$ZDOTDIR/startup.zsh"

