#!/usr/bin/zsh
#        _                        _            ___  _  _
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|
#
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#      
# zsh config

# ---------------------------------------------------------
# CHECK IF RUNNING IN INTERACTIVE MODE
# ---------------------------------------------------------
[[ -o interactive ]] || exit

# ---------------------------------------------------------
# SOURCE OTHER FILES
# ---------------------------------------------------------
source "$ZDOTDIR/cursor.zsh"
source "$ZDOTDIR/abbreviations.zsh"
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/bookmarks.zsh"
source "$ZDOTDIR/functions.zsh"
[ -f "$XDG_CONFIG_HOME/colors.sh" ] && source "$XDG_CONFIG_HOME/colors.sh"

# ---------------------------------------------------------
# HISTORY CONFIGURATION
# ---------------------------------------------------------
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
HISTORY_IGNORE="(git add *|git commit *|* _bookmark-ls|mpv http*)"
HISTFILE="$XDG_CACHE_HOME/zsh/zsh_history"
HISTSIZE=15000
SAVEHIST=15000

# ---------------------------------------------------------
# AUTOCOMPLETION
# ---------------------------------------------------------
autoload -U compinit
zstyle :compinstall filename "$XDG_CONFIG_HOME/zsh/zshrc"
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_com_options+=(globdots)

# ---------------------------------------------------------
# CD INTO FOLDER SELECTED USING LF OR FZF
# ---------------------------------------------------------
# from https://github.com/LukeSmithxyz/voidrice/blob/master/.config/zsh/.zshrc
lfcd(){
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp" >/dev/null
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}

fzfcd(){
  dest="$(cat "$DOTFILES_REPO/bookmarks/source-"* | awk '{print $2}' | sort | fzf)"
  [ -z "$dest" ] && return
  cd "$(eval "echo $dest")"
}

# ---------------------------------------------------------
# KEYBINDINGS
# ---------------------------------------------------------
KEYTIMEOUT=3
bindkey -v # vi mode
# vi navigation in menu
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
# edit command in editor
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

bindkey -s '^f' 'lfcd\n' # select folder to open with lf
bindkey -s '^o' 'fzfcd\n' # select folder to open with fzf
bindkey -s '^b' ' &>/dev/null & disown' # run command in the background

# ---------------------------------------------------------
# OTHER SETTINGS
# ---------------------------------------------------------
setopt autocd
unsetopt beep extendedglob notify

# ---------------------------------------------------------
# PROMPT
# ---------------------------------------------------------
case "$TERM" in
  xterm*) export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship.toml" ;;
  *)      export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship-ascii.toml" ;;
esac
eval "$(starship init zsh)"

# ---------------------------------------------------------
# SYNTAX HIGHLIGHTING
# ---------------------------------------------------------
ZSH_SYNTAX="+ZSH_SYNTAX_PLUGIN+"
[ -f "$ZSH_SYNTAX" ] && source "$ZSH_SYNTAX"
unset ZSH_SYNTAX

# ---------------------------------------------------------
# STARTUP STUFF IF NOT INSIDE LF
# ---------------------------------------------------------
[ -z "$LF_LEVEL" ] && source "$ZDOTDIR/startup.zsh"

