#!/bin/sh

CONFIG_DIR="$XDG_CONFIG_HOME/fish"

echo "Cleaning config directory..."
rm -rv "$CONFIG_DIR/"*
mkdir -p "$CONFIG_DIR"

cp -rv "static/"* "$CONFIG_DIR/"
echo "dynamic/config.fish -> $CONFIG_DIR/config.fish"
cat "dynamic/config.fish" | ../reconf \
    > "$CONFIG_DIR/config.fish"
echo "creating bookmarks"
pre="$(pwd)"
cd "../bookmarks" && ./build fish > "$CONFIG_DIR/bookmarks.fish"
cd "$pre"

echo "WARN: the fish install script does not use unified shell aliases yet"

../install starship

