#!/bin/bash
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#                                                          
# .bashrc

# ---------------------------------------------------------
# ENVIROMENTAL VARIABLES
# ---------------------------------------------------------
source "$HOME/.local/share/bash/env.bash"

# ---------------------------------------------------------
# ALIASES
# ---------------------------------------------------------
if [ -f "$XDG_DATA_HOME/bash/aliases.bash" ]; then
    . "$XDG_DATA_HOME/bash/aliases.bash"
fi

# ---------------------------------------------------------
# If not running interactively, don't do anything
# ---------------------------------------------------------
case $- in
    *i*) ;;
      *) return;;
esac

# ---------------------------------------------------------
# HISTORY OPTIONS
# ---------------------------------------------------------
HISTCONTROL=ignoreboth      # ignore lines starting with spaces
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s histappend         # append to the history file, don't overwrite it

# ---------------------------------------------------------
# SHOPT
# ---------------------------------------------------------
shopt -s autocd
shopt -s cdspell
shopt -s expand_aliases
shopt -s checkwinsize
bind "set completion-ignore-case on"

# ---------------------------------------------------------
# PROMPT
# ---------------------------------------------------------
PS1='[ \033[01;32m\u\033[00;31m@\033[01;34m\h\033[00m in \033[01;35m\w \033[00m]\033[01;36m \$\n \033[01;32m>>>\033[00m '
PS2=">> "

# ---------------------------------------------------------
# STUFF SHOWN ON STARTUP
# ---------------------------------------------------------
pfetch
echo -e "\033[01;32mWelcome back to the Bourne-Again-Shell, Alex! :D \n \033[00m"

