#!/bin/bash
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#                                                          
# .bashrc

# ---------------------------------------------------------
# ENVIROMENTAL VARIABLES
# ---------------------------------------------------------
source "$HOME/.local/share/bash/env.bash"

# ---------------------------------------------------------
# If not running interactively, don't do anything
# ---------------------------------------------------------
case $- in
    *i*) ;;
      *) return;;
esac

# ---------------------------------------------------------
# ALIASES
# ---------------------------------------------------------
[ -f "$XDG_DATA_HOME/bash/aliases.bash" ] && source "$XDG_DATA_HOME/bash/aliases.bash"
[ -f "$XDG_DATA_HOME/bash/bookmarks.bash" ] && source "$XDG_DATA_HOME/bash/bookmarks.bash"

# ---------------------------------------------------------
# HISTORY OPTIONS
# ---------------------------------------------------------
HISTCONTROL=ignoreboth
HISTFILE=$XDG_CACHE_HOME/bash_history
HISTSIZE=10000
HISTFILESIZE=10000
shopt -s histappend

# ---------------------------------------------------------
# SHOPTS
# ---------------------------------------------------------
shopt -s autocd
shopt -s cdspell
shopt -s expand_aliases
shopt -s checkwinsize
bind "set completion-ignore-case on"

# ---------------------------------------------------------
# PROMPT
# ---------------------------------------------------------
PS1='[ \[\e[01;36m\]\u\[\e[00;34m\]@\[\e[01;32m\]\h\[\e[00m\] in \[\e[01;34m\]\w \[\e[00m\]]\[\e[01;36m\] \$\n \[\e[01;34m\]>\[\e[01;36m\]>\[\e[01;32m\]>\[\e[00m\] '
PS2=">> "

# ---------------------------------------------------------
# STUFF SHOWN ON STARTUP
# ---------------------------------------------------------
pfetch
echo -e "\033[01;32mWelcome back to the Bourne-Again-Shell, $USER! :D \n \033[00m"

