#!/bin/bash
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#                                                          
# .bashrc

# ---------------------------------------------------------
# ENVIROMENTAL VARIABLES
# ---------------------------------------------------------

# PATH
export PATH="+ENV_PATH+"
# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
export XDG_CONFIG_DIRS="/etc/xdg"
# trick some programs to accept XDG
export HISTFILE="$XDG_DATA_HOME/bash/history"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export GOPATH="$XDG_DATA_HOME/go"

# settings
export TERMINAL="+TERMINAL_MAIN+"
export BROWSER="+BROWSER_MAIN+"
export EDITOR="+EDITOR_MAIN+"

# ---------------------------------------------------------
# If not running interactively, don't do anything
# ---------------------------------------------------------
case $- in
    *i*) ;;
      *) return;;
esac

# ---------------------------------------------------------
# HISTORY OPTIONS
# ---------------------------------------------------------
HISTCONTROL=ignoreboth      # ignore lines starting with spaces
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s histappend         # append to the history file, don't overwrite it

# ---------------------------------------------------------
# SHOPT
# ---------------------------------------------------------
shopt -s autocd
shopt -s cdspell
shopt -s expand_aliases
shopt -s checkwinsize
bind "set completion-ignore-case on"

# ---------------------------------------------------------
# PROMPT
# ---------------------------------------------------------
PS1='[ \033[01;32m\u\033[00;31m@\033[01;34m\h\033[00m in \033[01;35m\w \033[00m]\033[01;36m \$\n \033[01;32m>>>\033[00m '
PS2=">> "

# ---------------------------------------------------------
# ALIASES
# ---------------------------------------------------------
if [ -f "$XDG_DATA_HOME/bash/aliases" ]; then
    . "$XDG_DATA_HOME/bash/aliases"
fi

# ---------------------------------------------------------
# STUFF SHOWN ON STARTUP
# ---------------------------------------------------------
pfetch
echo -e "\033[01;32mWelcome back to the Bourne-Again-Shell, Alex! :D \n \033[00m"

