#!/bin/sh

DATA_DIR="$XDG_DATA_HOME/bash"

[ -d "$DATA_DIR" ] || mkdir -p "$DATA_DIR"

echo "./bashrc -> $HOME/.bashrc"
[ -f "options.$1" ] \
  && bashrc_files="./bashrc options.$1" \
  || bashrc_files="./bashrc"
echo "used files: $bashrc_files"
cat $bashrc_files | ../reconf "../defaults" "../$1.prefs" > "$HOME/.bashrc"

echo "../sh/env -> $DATA_DIR/env.bash"
cat "./_header" "../sh/env" | ../reconf "../defaults" "../$1.prefs" > "$DATA_DIR/env.bash"

echo "../sh/aliases -> $DATA_DIR/aliases.bash"
pre="$(pwd)"
cd "../sh" && ./aliases-gen "bash" > "$DATA_DIR/aliases.bash"
cd "$pre"

echo "creating bookmarks"
cd "../bookmarks" && ./build bash > "$DATA_DIR/bookmarks.bash"

