#!/bin/sh

DATA_DIR="$XDG_DATA_HOME/bash"

[ -d "$DATA_DIR" ] || mkdir -p "$DATA_DIR"

echo "bashrc -> $HOME/.bashrc"
cat "bashrc" | ../reconf "../defaults" "../$1.prefs" > "$HOME/.bashrc"
cp -v "aliases" "$DATA_DIR/aliases"

