#!/bin/sh

dir="$(pwd)"
case "$dir" in
		/media/drive/BILDER/*)
				file="$(printf "$dir" | sed "s/\/media\/drive\/BILDER\///")/$1"
				cd "/media/drive/BILDER/Wallpaper"
				[ -e "$1" ] && fname="$(date +%F-%r).$(printf "$1" | awk -F. '{print $NF}')" || fname="$1"
				ln -s "../$file" "$fname"
				notify-send "Added wallpaper" "$fname to /media/drive/BILDER/Wallpaper" ;;
		$HOME/*)
				file="$dir/$1"
				cp -v "$file" "$XDG_DATA_HOME/backgrounds/my-wallpapers/"
				notify-send "Copied wallpaper" "$1 to $XDG_DATA_HOME/backgrounds"
		*)
				notify-send -u critical "$dir is not allowed to add wallpapers" ;;
esac

