#!/bin/sh

TEMP_FOLDER="$HOME/tmp"
SHASUMS_FOLDER="/media/backup/SHASUMS"

fatal_error(){
		zenity --width 300 --error --text "$1"
		exit 1
}

progress_bar(){
		zenity --width 500 --progress --auto-close --text "$1" $2
}

check_shasum(){
		shasum_is="$(sha256sum "$filename" | awk '{print $1}')"
		shasum_must="$(cat "$filename.sha256sum")"
		if [ "$shasum_is" = "$shasum_must" ]; then
				if ! [ -e "$SHASUMS_FOLDER" ]; then
						zenity --width 300 --warning --text "global shasum could not be checked!"
						return
				fi
				shasum_must_global="$(cat "$SHASUMS_FOLDER/$filename.sha256sum")"
				if ! [ "$shasum_is" = "$shasum_must_global" ]; then
						fatal_error "shasum does not match the global shasum!"
				fi
		else
				fatal_error "shasums does not match!"
		fi
		zenity --width 300 --info --text "shasum test was successfull"
}

[ -z "$1" ] && fatal_error "You need to select a file or folder!"

cp "$1" "$TEMP_FOLDER/"
filename="$(printf "$1" | sed 's/.enc$//')"
if [ -f "$filename.sha256sum" ]; then
		cp "$filename.sha256sum" "$TEMP_FOLDER/"
else
		zenity --width 800 --question --text "no .sha256sum file exists. continue anyway?" \
				&& ignore_shasum="true" \
				|| exit 1
fi

cd "$TEMP_FOLDER"
password="$(zenity --width 300 --password)"
printf "$password" | alencrypt -d -r -s "$filename.enc" \
		| progress_bar "Your files are beeing decrypted..." \
		|| fatal_error "Files could not be decrypted!"

[ -f "$filename.sha256sum" ] && check_shasum
[ "$ignore_shasum" = "true" ] && check_shasum

bzip2 -d "$filename" \
		| progress_bar "archive is beeing decompressed..." "--pulsate"
tar -xf "$(printf "$filename" | sed 's/.bz2$//')" \
		| progress_bar "archive is beeing un-tar-ed..." "--pulsate" \
		&& rm "$(printf "$filename" | sed 's/.bz2$//')" "$filename.sha256sum"
zenity --width 800 --info --text "Your files are found in $TEMP_FOLDER/$(printf "$filename" | sed 's/.tar.bz2$//')"

