#!/bin/sh

TEMP_FOLDER="$HOME/tmp"
SHASUM_FOLDER="/media/backup/SHASUMS"

fatal_error(){
		zenity --width 300 --error --text "$1"
		exit 1
}

progress_bar(){
		zenity --width 500 --progress --auto-close --text "$1" $2
}

[ -z "$1" ] && fatal_error "You need to select a file or folder!"

out_file="$(zenity --width 500 --entry --entry-text "$1-$(date "+%Y%m%d")" --text "enter a name for the archive (without file extension)")"

if [ -d "$1" ]; then
		in_file="$(printf "$1" | tr -d "/")"
		tar -cf "$TEMP_FOLDER/$out_file.tar" "$in_file" \
				| progress_bar ".tar-archive is created" "--pulsate"
		filename="$out_file.tar"
else
		cp "$1" "$TEMP_FOLDER/$1"
		filename="$1"
fi
cd "$TEMP_FOLDER"
bzip2 "$filename" \
		| progress_bar "archive is beeing compressed..." "--pulsate"
sha256sum "$filename.bz2" \
		| awk '{print $1}' > "$filename.bz2.sha256sum" \
		| progress_bar "sha256sum is beeing calculated..." "--pulsate"
if [ -d "$SHASUM_FOLDER" ]; then
		cp "$filename.bz2.sha256sum" "$SHASUM_FOLDER/$filename.bz2.sha256sum" \
				&& extra_info="copy of the checksum saved to $SHASUM_FOLDER/$filename.bz2.sha256sum"
else
		zenity --width 300 --warning --text "Global shasum folder does not exist!\nThe shasum will not be copied automaticly" \
				&& extra_info="shasum could not be saved to the external folder!"
fi
pass1="$(zenity --password)"
pass2="$(zenity --password --text="Confirm password")"
[ "$pass1" = "$pass2" ] \
		|| fatal_error "Passwords do not match!"
printf "$pass1" | $HOME/bin/alencrypt -e -r -s -p "$filename.bz2" \
		| progress_bar "Encrypting file..." \
		|| fatal_error "Could not encrypt file"
zenity --width 800 --info --text "encrypted file was saved to $TEMP_FOLDER/$filename.enc\nchecksum saved to $TEMP_FOLDER/$filename.sha256sum\n$extra_info"

